[build]
target = "static\\index.html"
release = false
dist = "dist"

[watch]
path = ["src", "static"]
ignore = []

[serve]
port = 8080
open = false

[clean]
dist = "dist"
cargo = false

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:8081/"
